"use client";

import { useEffect, useMemo, useState } from "react";
import { readUnifiedCreations, type UnifiedCreation } from "../lib/creatorCollegeStore";

type BrandProject={id:string;name:string;brandType:string;purpose:string;audience:string;position:string;promise:string;personality:string;style:string;tagline:string;shortDescription:string;voice:string;assets:string[];connectedIds:string[];step:number;progress:number;status:"BUILDING"|"COMPLETE";updatedAt:string};
const KEY="creator-college-v1-brand-projects";
const ACTIVE="creator-college-v1-brand-active";
const steps=["Purpose","Audience","Position","Name","Identity","Message","Assets","Connect Creations","Launch","Review"];
function blank():BrandProject{return{id:`brand-${Date.now()}`,name:"Untitled Brand",brandType:"Creator / Media",purpose:"",audience:"",position:"",promise:"",personality:"Warm",style:"Modern",tagline:"",shortDescription:"",voice:"Conversational",assets:["Brand Name","Tagline","Short Description","Social Bio","About Blurb"],connectedIds:[],step:0,progress:5,status:"BUILDING",updatedAt:new Date().toISOString()}}
export default function BrandBuilderPage(){
 const[project,setProject]=useState<BrandProject|null>(null);const[creations,setCreations]=useState<UnifiedCreation[]>([]);const[saved,setSaved]=useState(true);
 useEffect(()=>{const list=JSON.parse(localStorage.getItem(KEY)||"[]") as BrandProject[];const id=localStorage.getItem(ACTIVE);setProject(list.find(x=>x.id===id&&x.status==="BUILDING")||blank());setCreations(readUnifiedCreations())},[]);
 useEffect(()=>{if(!project)return;setSaved(false);const t=setTimeout(()=>{const list=JSON.parse(localStorage.getItem(KEY)||"[]") as BrandProject[];const next=[project,...list.filter(x=>x.id!==project.id)];localStorage.setItem(KEY,JSON.stringify(next));localStorage.setItem(ACTIVE,project.status==="BUILDING"?project.id:"");setSaved(true)},350);return()=>clearTimeout(t)},[project]);
 const current=project?.step??0;const candidateCount=creations.filter(c=>c.status==="COMPLETE").length;
 function patch(v:Partial<BrandProject>){setProject(p=>p?{...p,...v,updatedAt:new Date().toISOString()}:p)}
 function next(){if(!project)return;const n=Math.min(project.step+1,steps.length-1);patch({step:n,progress:Math.round(((n+1)/steps.length)*100)})}
 function toggleCreation(id:string){if(!project)return;patch({connectedIds:project.connectedIds.includes(id)?project.connectedIds.filter(x=>x!==id):[...project.connectedIds,id]})}
 function complete(){if(!project)return;patch({status:"COMPLETE",progress:100});setTimeout(()=>localStorage.setItem(ACTIVE,""),0)}
 if(!project)return null;
 return <main className="cc4-shell"><section className="cc4-hero"><span className="cc4-eyebrow">BRAND HALL · STARTER BRAND BUILDER</span><h1>TURN WHAT YOU MAKE INTO SOMETHING PEOPLE RECOGNIZE.</h1><p>{saved?"Saved ✓":"Saving…"}</p></section>
 {candidateCount>=2&&<section className="cc5-smart-panel"><div><span className="cc4-eyebrow">CREATOR COACH</span><h2>YOU MAY HAVE A BRAND HERE.</h2><p>You already have {candidateCount} finished creations. Brand Hall can organize them under one recognizable identity.</p></div></section>}
 <section className="cc5-smart-panel"><div><span className="cc4-eyebrow">{steps[current]} · STEP {current+1} OF {steps.length}</span><h2>{steps[current]}</h2><div className="cc4-meter"><span style={{width:`${project.progress}%`}}/></div></div></section><section className="cc4-section">
 {current===0&&<article className="cc5-profile-card"><h2>What kind of brand is this?</h2><div className="cc5-chips">{["Personal Brand","Product Brand","Business Brand","Organization / Church","Creator / Media","Event Brand","Family / Community"].map(x=><button key={x} className={project.brandType===x?"selected":""} onClick={()=>patch({brandType:x})}>{x}</button>)}</div><textarea value={project.purpose} onChange={e=>patch({purpose:e.target.value})} placeholder="What do you want this brand to stand for or help people do?"/><button className="cc4-primary" disabled={!project.purpose.trim()} onClick={next}>KEEP THIS PURPOSE</button></article>}
 {current===1&&<article className="cc5-profile-card"><h2>Who is this brand for?</h2><input value={project.audience} onChange={e=>patch({audience:e.target.value})} placeholder="Describe the people this brand should matter to"/><button className="cc4-primary" disabled={!project.audience.trim()} onClick={next}>NEXT</button></article>}
 {current===2&&<article className="cc5-profile-card"><h2>What makes it distinct?</h2><textarea value={project.position} onChange={e=>patch({position:e.target.value})} placeholder="We help ___ get ___ through ___"/><textarea value={project.promise} onChange={e=>patch({promise:e.target.value})} placeholder="What should people consistently expect from this brand?"/><button className="cc4-primary" disabled={!project.position.trim()} onClick={next}>KEEP THIS POSITION</button></article>}
 {current===3&&<article className="cc5-profile-card"><h2>Name the brand</h2><input value={project.name==="Untitled Brand"?"":project.name} onChange={e=>patch({name:e.target.value||"Untitled Brand"})} placeholder="Brand name"/><input value={project.tagline} onChange={e=>patch({tagline:e.target.value})} placeholder="Optional tagline"/><button className="cc4-primary" disabled={project.name==="Untitled Brand"} onClick={next}>USE THIS NAME</button></article>}
 {current===4&&<article className="cc5-profile-card"><h2>Choose the identity direction</h2><div className="cc5-chips">{["Clean","Luxury","Modern","Heritage","Faith","Playful","Professional","Bold","Community"].map(x=><button key={x} className={project.style===x?"selected":""} onClick={()=>patch({style:x})}>{x}</button>)}</div><div className="cc5-chips">{["Warm","Direct","Encouraging","Professional","Bold","Conversational","Faith-centered","Fun"].map(x=><button key={x} className={project.voice===x?"selected":""} onClick={()=>patch({voice:x})}>{x}</button>)}</div><button className="cc4-primary" onClick={next}>USE THIS IDENTITY</button></article>}
 {current===5&&<article className="cc5-profile-card"><h2>Shape the message</h2><textarea value={project.shortDescription} onChange={e=>patch({shortDescription:e.target.value})} placeholder="One short paragraph that explains the brand clearly"/><p><b>Brand promise:</b> {project.promise||"Add your promise in the Position step."}</p><button className="cc4-primary" onClick={next}>BUILD STARTER ASSETS</button></article>}
 {current===6&&<article className="cc5-profile-card"><h2>Your starter brand kit</h2><div className="cc4-family-items">{project.assets.map((a,i)=><div key={a}><span>✓</span><div><b>{a}</b><small>{i===0?project.name:i===1?(project.tagline||"Tagline ready to refine"):i===2?(project.shortDescription||project.position):`${project.voice} voice · ${project.style} identity`}</small></div></div>)}</div><button className="cc4-primary" onClick={next}>CONNECT MY CREATIONS</button></article>}
 {current===7&&<article className="cc5-profile-card"><h2>What belongs under this brand?</h2><div className="cc4-card-grid cc4-grid">{creations.length===0?<div className="cc4-empty">Finish a creation first, or continue building this brand now and connect things later.</div>:creations.map(c=><button key={`${c.kind}-${c.id}`} className={`cc5-brand-connect ${project.connectedIds.includes(c.id)?"selected":""}`} onClick={()=>toggleCreation(c.id)}><small>{c.kind.replaceAll("_"," ")}</small><b>{c.title}</b><span>{project.connectedIds.includes(c.id)?"CONNECTED":"CONNECT"}</span></button>)}</div><button className="cc4-primary" onClick={next}>KEEP THESE CONNECTIONS</button></article>}
 {current===8&&<article className="cc5-profile-card"><h2>Introduce the brand</h2><div className="cc4-card-grid cc4-grid"><div className="cc4-card"><small>ANNOUNCEMENT</small><h3>{project.name} is here.</h3><p>{project.shortDescription||project.position}</p></div><div className="cc4-card"><small>SOCIAL BIO</small><h3>{project.name}</h3><p>{project.tagline||project.promise}</p></div><div className="cc4-card"><small>FIRST MOVE</small><h3>Lead with one creation</h3><p>{project.connectedIds.length?"Choose your strongest connected creation as the first proof of the brand.":"Connect or create one strong proof piece next."}</p></div></div><button className="cc4-primary" onClick={next}>REVIEW MY BRAND</button></article>}
 {current===9&&project.status!=="COMPLETE"&&<article className="cc5-profile-card"><h2>Your starter brand is ready</h2><div className="cc4-review-list"><div><span>✓</span><b>Purpose</b><small>{project.purpose}</small></div><div><span>✓</span><b>Audience</b><small>{project.audience}</small></div><div><span>✓</span><b>Position</b><small>{project.position}</small></div><div><span>✓</span><b>Identity</b><small>{project.style} · {project.voice}</small></div><div><span>✓</span><b>Connected creations</b><small>{project.connectedIds.length} connected</small></div></div><button className="cc4-primary" onClick={complete}>COMPLETE MY STARTER BRAND</button></article>}
 {project.status==="COMPLETE"&&<article className="cc5-smart-panel"><div><span className="cc4-eyebrow">STARTER BRAND COMPLETE</span><h2>{project.name} IS READY TO GROW.</h2><p>{project.brandType} · {project.connectedIds.length} connected creations · {project.style} identity</p><div className="cc4-grid cc4-actions-grid"><a href="/creator-college/brand-hall">◇<b>OPEN BRAND HALL</b><small>See brands and connected creations</small></a><a href="/creator-college/service">💼<b>BUILD AN OFFER</b><small>Turn the brand into a simple commercial path</small></a></div></div></article>}
 </section></main>
}
