"use client";

import { useEffect, useState } from "react";

type Asset={name:string;content:string};
type EventProject={id:string;title:string;eventType:string;purpose:string;audience:string;feeling:string;tagline:string;style:string;timeline:string[];promo:Asset[];materials:Asset[];followup:string;step:number;progress:number;status:"BUILDING"|"COMPLETE";updatedAt:string;familyId?:string;parentId?:string};
const KEY="creator-college-v1-event-projects";
const ACTIVE="creator-college-v1-event-active";
const steps=["Idea","Purpose","Audience","Event Identity","Plan","Promotion","Materials","Experience","Follow-Up","Review"];
function blank():EventProject{return{id:`event-${Date.now()}`,title:"Untitled Event",eventType:"Church Event",purpose:"Bring people together",audience:"",feeling:"Connected",tagline:"",style:"Warm",timeline:[],promo:[],materials:[],followup:"",step:0,progress:5,status:"BUILDING",updatedAt:new Date().toISOString()}}
function coachPlan(p:EventProject){return["BEFORE · Confirm purpose, date, place and team","BEFORE · Open registration / invitations","BEFORE · Send reminder and final details","DURING · Welcome + clear opening","DURING · Main experience + interaction","DURING · Closing action / next step","AFTER · Thank-you + follow-up","AFTER · Capture feedback / next gathering"]}
function promoPack(p:EventProject):Asset[]{return[{name:"Flyer Copy",content:`${p.title}\n${p.tagline||p.purpose}\nCreated for ${p.audience}.`},{name:"Social Post",content:`You’re invited to ${p.title}. Come ready to feel ${p.feeling.toLowerCase()} and leave with a clear next step.`},{name:"Text Invite",content:`Join us for ${p.title}. We’d love to have you with us.`},{name:"Announcement",content:`Save the date for ${p.title}, created to ${p.purpose.toLowerCase()}.`} ]}
function materialPack(p:EventProject):Asset[]{return[{name:"Welcome Message",content:`Welcome to ${p.title}. We’re glad you’re here.`},{name:"Simple Agenda",content:"Welcome\nOpening\nMain Experience\nInteraction\nClosing / Next Step"},{name:"Volunteer Checklist",content:"Arrive early\nConfirm setup\nWelcome guests\nSupport program flow\nHelp with follow-up"},{name:"Table / Discussion Prompt",content:`What would help you leave today feeling more ${p.feeling.toLowerCase()}?`} ]}
export default function EventBuilderPage(){
 const[project,setProject]=useState<EventProject|null>(null);const[saved,setSaved]=useState(true);
 useEffect(()=>{const list=JSON.parse(localStorage.getItem(KEY)||"[]") as EventProject[];const id=localStorage.getItem(ACTIVE);setProject(list.find(x=>x.id===id&&x.status==="BUILDING")||blank())},[]);
 useEffect(()=>{if(!project)return;setSaved(false);const t=setTimeout(()=>{const list=JSON.parse(localStorage.getItem(KEY)||"[]") as EventProject[];const next=[project,...list.filter(x=>x.id!==project.id)];localStorage.setItem(KEY,JSON.stringify(next));localStorage.setItem(ACTIVE,project.status==="BUILDING"?project.id:"");setSaved(true)},350);return()=>clearTimeout(t)},[project]);
 function patch(v:Partial<EventProject>){setProject(p=>p?{...p,...v,updatedAt:new Date().toISOString()}:p)}
 function next(){if(!project)return;const n=Math.min(project.step+1,steps.length-1);patch({step:n,progress:Math.round(((n+1)/steps.length)*100)})}
 function complete(){if(!project)return;patch({status:"COMPLETE",progress:100,familyId:project.familyId||`family-${project.id}`});setTimeout(()=>localStorage.setItem(ACTIVE,""),0)}
 if(!project)return null;const s=project.step;
 return <main className="cc4-shell"><section className="cc4-hero"><span className="cc4-eyebrow">CREATOR LAB · CHURCH / GROUP EVENT KIT</span><h1>TURN YOUR EVENT IDEA INTO A COMPLETE EVENT PACKAGE.</h1><p>{saved?"Saved ✓":"Saving…"}</p></section><section className="cc5-smart-panel"><div><span className="cc4-eyebrow">{steps[s]} · STEP {s+1} OF {steps.length}</span><h2>{steps[s]}</h2><div className="cc4-meter"><span style={{width:`${project.progress}%`}}/></div></div></section><section className="cc4-section">
 {s===0&&<article className="cc5-profile-card"><h2>What are you planning?</h2><div className="cc5-chips">{["Church Event","Group Gathering","Workshop","Celebration","Community Outreach","Family Event","Class","Other"].map(x=><button key={x} className={project.eventType===x?"selected":""} onClick={()=>patch({eventType:x})}>{x}</button>)}</div><input value={project.title==="Untitled Event"?"":project.title} onChange={e=>patch({title:e.target.value||"Untitled Event"})} placeholder="Event name or working idea"/><button className="cc4-primary" disabled={project.title==="Untitled Event"} onClick={next}>USE THIS EVENT</button></article>}
 {s===1&&<article className="cc5-profile-card"><h2>What is this event meant to do?</h2><div className="cc5-chips">{["Bring people together","Teach","Celebrate","Reach new people","Raise support","Build community","Create memories","Launch something","Serve"].map(x=><button key={x} className={project.purpose===x?"selected":""} onClick={()=>patch({purpose:x})}>{x}</button>)}</div><button className="cc4-primary" onClick={next}>KEEP THIS PURPOSE</button></article>}
 {s===2&&<article className="cc5-profile-card"><h2>Who is this for?</h2><input value={project.audience} onChange={e=>patch({audience:e.target.value})} placeholder="Example: church families, neighborhood parents, volunteers, teens"/><button className="cc4-primary" disabled={!project.audience.trim()} onClick={next}>NEXT</button></article>}
 {s===3&&<article className="cc5-profile-card"><h2>Give the event an identity</h2><input value={project.title} onChange={e=>patch({title:e.target.value})}/><input value={project.tagline} onChange={e=>patch({tagline:e.target.value})} placeholder="Tagline or theme line"/><div className="cc5-chips">{["Warm","Bold","Elegant","Modern","Faith","Community"].map(x=><button key={x} className={project.style===x?"selected":""} onClick={()=>patch({style:x})}>{x}</button>)}</div><button className="cc4-primary" onClick={()=>{patch({timeline:coachPlan(project)});next()}}>BUILD MY EVENT PLAN</button></article>}
 {s===4&&<article className="cc5-profile-card"><h2>Before · During · After</h2><div className="cc4-family-items">{project.timeline.map((x,i)=><div key={i}><span>{i+1}</span><div><input value={x} onChange={e=>patch({timeline:project.timeline.map((t,idx)=>idx===i?e.target.value:t)})}/></div></div>)}</div><button className="cc4-primary" onClick={()=>{patch({promo:promoPack(project)});next()}}>CREATE PROMOTION</button></article>}
 {s===5&&<article className="cc5-profile-card"><h2>Your promotion pack</h2><div className="cc4-card-grid cc4-grid">{project.promo.map((a,i)=><div className="cc4-card" key={a.name}><small>PROMOTION</small><h3>{a.name}</h3><textarea value={a.content} onChange={e=>patch({promo:project.promo.map((x,idx)=>idx===i?{...x,content:e.target.value}:x)})}/></div>)}</div><button className="cc4-primary" onClick={()=>{patch({materials:materialPack(project)});next()}}>BUILD EVENT MATERIALS</button></article>}
 {s===6&&<article className="cc5-profile-card"><h2>Event materials</h2><div className="cc4-card-grid cc4-grid">{project.materials.map((a,i)=><div className="cc4-card" key={a.name}><small>MATERIAL</small><h3>{a.name}</h3><textarea value={a.content} onChange={e=>patch({materials:project.materials.map((x,idx)=>idx===i?{...x,content:e.target.value}:x)})}/></div>)}</div><button className="cc4-primary" onClick={next}>DESIGN THE EXPERIENCE</button></article>}
 {s===7&&<article className="cc5-profile-card"><h2>How should people feel?</h2><div className="cc5-chips">{["Inspired","Connected","Educated","Celebrated","Motivated","Supported","Changed"].map(x=><button key={x} className={project.feeling===x?"selected":""} onClick={()=>patch({feeling:x})}>{x}</button>)}</div><p>Creator Coach suggestion: open with a strong welcome, create one intentional interaction, give people one memory point, and close with one clear next action.</p><button className="cc4-primary" onClick={next}>USE THIS EXPERIENCE</button></article>}
 {s===8&&<article className="cc5-profile-card"><h2>What happens after the event?</h2><textarea value={project.followup} onChange={e=>patch({followup:e.target.value})} placeholder="Thank-you, feedback, next event, resource, community invitation..."/><button className="cc4-primary" onClick={next}>REVIEW MY KIT</button></article>}
 {s===9&&project.status!=="COMPLETE"&&<article className="cc5-profile-card"><h2>Your event kit is ready to finish</h2><div className="cc4-review-list"><div><span>✓</span><b>Event identity</b><small>{project.title} · {project.style}</small></div><div><span>✓</span><b>Audience + purpose</b><small>{project.audience} · {project.purpose}</small></div><div><span>✓</span><b>Timeline</b><small>{project.timeline.length} before/during/after steps</small></div><div><span>✓</span><b>Promotion + materials</b><small>{project.promo.length} promo assets · {project.materials.length} event materials</small></div></div><button className="cc4-primary" onClick={complete}>COMPLETE MY EVENT KIT</button></article>}
 {project.status==="COMPLETE"&&<article className="cc5-smart-panel"><div><span className="cc4-eyebrow">EVENT KIT COMPLETE</span><h2>{project.title} IS READY TO RUN.</h2><p>{project.eventType} · {project.timeline.length} plan steps · {project.promo.length+project.materials.length} ready-to-use assets</p><div className="cc4-grid cc4-actions-grid"><a href="/creator-college/locker">▦<b>SAVE TO LOCKER</b><small>Keep it with your other creations</small></a><a href="/creator-college/event">⧉<b>MAKE ANOTHER EVENT KIT</b><small>Reuse the event system</small></a></div></div></article>}
 </section></main>
}
