from pathlib import Path
import json,re
p=Path(__file__).resolve().parent.parent/'theme/sections/network-eve-report.liquid'
s=p.read_text()
s=s.replace('class="eve-hero-copy"','class="eve-hero-copy" data-eve-story data-story-title="{{ section.settings.hero_heading | escape }}" data-story-url="{{ section.settings.story_link | escape }}"')
s=s.replace('<article class="eve-five-item">','''{% assign field_prefix = 'five_' | append: idx %}
          {% assign title_key = field_prefix | append: '_title' %}{% assign copy_key = field_prefix | append: '_copy' %}{% assign link_key = field_prefix | append: '_link' %}{% assign question_key = field_prefix | append: '_question' %}{% assign scripture_key = field_prefix | append: '_scripture' %}
          {% assign story_title = section.settings[title_key] | default: label %}
          {% assign story_copy = section.settings[copy_key] | default: five_copy[forloop.index0] %}
          {% assign story_link = section.settings[link_key] %}
          <article class="eve-five-item" data-eve-story data-story-title="{{ story_title | escape }}" data-story-url="{{ story_link | escape }}">''')
s=s.replace('<h4>{{ label }}</h4><p>{{ five_copy[forloop.index0] }}</p>','''<h4>{{ story_title | escape }}</h4><p>{{ story_copy | escape }}</p>
            {% if story_link != blank %}<div class="eve-card-actions"><a href="{{ story_link }}">Read It →</a><button type="button" data-eve-share>Send to a Sister</button><button type="button" data-eve-save aria-pressed="false"><span>♡</span> Save</button><button type="button" data-eve-gather data-gp-story-url="{{ story_link | escape }}" data-gp-story-id="{{ field_prefix }}" data-gp-story-headline="{{ story_title | escape }}" data-gp-story-question="{{ section.settings[question_key] | escape }}" data-gp-story-scripture="{{ section.settings[scripture_key] | escape }}">Gather Around This ↓</button></div><p data-eve-status role="status" aria-live="polite"></p>{% endif %}''')
start=s.index('<script>');end=s.index('</script>',start)+len('</script>')
s=s[:start]+'''<script>(function(){const r=document.getElementById({{ sid | json }});if(!r)return;r.querySelectorAll('[data-eve-story]').forEach(story=>{const note=story.querySelector('[data-eve-status]');const sh=story.querySelector('[data-eve-share]');const getUrl=()=>new URL(story.dataset.storyUrl||sh.dataset.shareUrl||location.pathname,location.origin).href;if(sh)sh.addEventListener('click',async()=>{const d={title:story.dataset.storyTitle||'The EVE Report — Women of Color',text:'Something from The EVE Report worth sharing.',url:getUrl()};try{if(navigator.share)await navigator.share(d);else{await navigator.clipboard.writeText(d.url);note.textContent='Link copied. Paste it into a message to your sister.';}}catch(e){if(e.name!=='AbortError')note.textContent='Share this page by copying its address from your browser.';}});const s=story.querySelector('[data-eve-save]');if(s)s.addEventListener('click',()=>{try{const url=getUrl();const existing=JSON.parse(localStorage.getItem('woc-eve-saved')||'[]');const saved=Array.isArray(existing)?existing:[];if(!saved.includes(url))saved.push(url);localStorage.setItem('woc-eve-saved',JSON.stringify(saved.slice(-50)));note.replaceChildren(document.createTextNode('Saved in this browser. '));const a=document.createElement('a');a.href=url;a.textContent='Open saved story';a.style.color='inherit';note.append(a);s.setAttribute('aria-pressed','true');s.querySelector('span').textContent='♥';}catch(e){note.textContent='Browser saving is unavailable. Bookmark this story to keep it.';}});});})();</script>'''+s[end:]
m=re.search(r'{% schema %}(.*?){% endschema %}',s,re.S);schema=json.loads(m.group(1))
for idx in range(1,6):
    for kind,suffix,label in [('text','title','Headline'),('textarea','copy','Summary'),('url','link','Story link'),('textarea','question','Gathering question'),('text','scripture','Optional Scripture reference')]:
        schema['settings'].append({'type':kind,'id':f'five_{idx}_{suffix}','label':f'Five {idx} — {label}'})
s=s[:m.start(1)]+json.dumps(schema)+s[m.end(1):]
s+='\n<style>#{{ sid }} .eve-card-actions{display:grid;gap:8px;margin-top:18px}#{{ sid }} .eve-card-actions a,#{{ sid }} .eve-card-actions button{display:flex;align-items:center;justify-content:center;min-height:44px;padding:8px;border:1px solid #b69955;border-radius:7px;color:#f3e5c3;background:transparent;font:15px Georgia,serif;text-decoration:none;cursor:pointer}#{{ sid }} .eve-card-actions [data-eve-gather]{background:#54203e}#{{ sid }} [data-eve-status]{font:14px/1.4 Arial;color:#f4e3bd}</style>\n'
p.write_text(s)
