"use client";

import { useEffect, useMemo, useState } from "react";
import { readUnifiedCreations, type UnifiedCreation } from "../lib/creatorCollegeStore";

type BrandProject={id:string;name:string;brandType:string;purpose:string;audience:string;position:string;promise:string;personality:string;style:string;tagline:string;shortDescription:string;voice:string;assets:string[];connectedIds:string[];step:number;progress:number;status:"BUILDING"|"COMPLETE";updatedAt:string};
const BRAND_KEY="creator-college-v1-brand-projects";

export default function BrandHallPage(){
 const[brands,setBrands]=useState<BrandProject[]>([]);const[creations,setCreations]=useState<UnifiedCreation[]>([]);
 useEffect(()=>{setBrands(JSON.parse(localStorage.getItem(BRAND_KEY)||"[]"));setCreations(readUnifiedCreations())},[]);
 const finished=useMemo(()=>creations.filter(c=>c.status==="COMPLETE"),[creations]);
 const unbranded=useMemo(()=>finished.filter(c=>c.kind!=="business"&&!brands.some(b=>b.connectedIds.includes(c.id))),[finished,brands]);
 const businessReady=useMemo(()=>brands.some(b=>b.status==="COMPLETE")||finished.some(c=>c.kind==="service_offer"),[brands,finished]);
 return <main className="cc4-shell"><section className="cc4-hero"><span className="cc4-eyebrow">BRAND HALL</span><h1>ORGANIZE WHAT YOU MAKE INTO SOMETHING PEOPLE RECOGNIZE.</h1><p>Brands sit above individual creations. They should make your work easier to understand, reuse, and grow.</p></section>
 {finished.length>=2&&brands.length===0&&<section className="cc5-smart-panel"><div><span className="cc4-eyebrow">CREATOR COACH</span><h2>YOU MAY HAVE A BRAND HERE.</h2><p>You have {finished.length} finished creations. That is enough to test whether they belong under one recognizable identity.</p></div><a className="cc4-primary" href="/creator-college/brand">BUILD MY STARTER BRAND</a></section>}
 {businessReady&&<section className="cc5-smart-panel"><div><span className="cc4-eyebrow">BUSINESS CENTER</span><h2>YOU MAY HAVE A BUSINESS HERE.</h2><p>You now have enough proof—a finished brand, service, or offer—to test a simple operating business system.</p></div><a className="cc4-primary" href="/creator-college/business">BUILD MY BUSINESS SYSTEM</a></section>}
 <section className="cc4-section"><div className="cc4-section-head"><div><span className="cc4-eyebrow">MY BRANDS</span><h2>BRANDS IN PROGRESS</h2></div><a href="/creator-college/brand">+ NEW BRAND</a></div>{brands.length===0?<div className="cc4-empty">No brands yet. Creator College will suggest one when your creations begin to form a pattern.</div>:<div className="cc4-grid cc4-card-grid">{brands.map(brand=>{const connected=creations.filter(c=>brand.connectedIds.includes(c.id));return <article className="cc4-card" key={brand.id}><small>{brand.status} · {brand.brandType}</small><h3>{brand.name}</h3><p>{brand.tagline||brand.promise||brand.position}</p><p><b>{brand.style}</b> identity · <b>{brand.voice}</b> voice</p><div className="cc4-meter"><span style={{width:`${brand.progress}%`}}/></div><b>{connected.length} connected creation{connected.length===1?"":"s"}</b><div className="cc4-mini-actions"><a href="/creator-college/brand">{brand.status==="BUILDING"?"CONTINUE":"OPEN BRAND"}</a>{brand.status==="COMPLETE"&&<a href="/creator-college/business">BUILD BUSINESS</a>}</div></article>})}</div>}</section>
 <section className="cc4-section"><div className="cc4-section-head"><div><span className="cc4-eyebrow">CONNECTED WORK</span><h2>WHAT EACH BRAND CONTAINS</h2></div></div>{brands.map(brand=>{const connected=creations.filter(c=>brand.connectedIds.includes(c.id));return <article className="cc4-family" key={brand.id}><div className="cc4-family-head"><div><small>BRAND</small><h3>{brand.name}</h3></div><b>{connected.length} items</b></div><div className="cc4-family-items">{connected.length?connected.map(item=><div key={`${item.kind}-${item.id}`}><span>✓</span><div><b>{item.title}</b><small>{item.kind.replaceAll("_"," ")} · {item.format}</small></div><div className="cc4-mini-actions"><a href={item.route}>OPEN</a></div></div>):<div><span>◌</span><div><b>No creations connected yet</b><small>Open the brand builder and connect your strongest proof pieces.</small></div></div>}</div></article>})}</section>
 <section className="cc4-section"><div className="cc4-section-head"><div><span className="cc4-eyebrow">UNBRANDED CREATIONS</span><h2>WORK THAT MAY NEED A HOME</h2></div><span>{unbranded.length}</span></div>{unbranded.length===0?<div className="cc4-empty">Everything finished is already connected, or you have not finished enough work yet.</div>:<div className="cc4-grid cc4-card-grid">{unbranded.map(item=><article className="cc4-card" key={`${item.kind}-${item.id}`}><small>{item.kind.replaceAll("_"," ")}</small><h3>{item.title}</h3><p>{item.format}</p><a href="/creator-college/brand">CONNECT TO A BRAND</a></article>)}</div>}</section>
 </main>
}
