"use client";

import { useEffect, useMemo, useState } from "react";
import { readUnifiedCreations, type UnifiedCreation } from "../lib/creatorCollegeStore";

type BusinessProject={id:string;name:string;sourceId:string;customer:string;offer:string;delivery:string;pricePosition:string;salesMessage:string;operations:string[];growth:string;step:number;progress:number;status:"BUILDING"|"COMPLETE";updatedAt:string};
const KEY="creator-college-v1-business-projects";
const ACTIVE="creator-college-v1-business-active";
const steps=["Business Idea","Customer","Offer","Delivery","Price","Sales","Operations","Growth","Review"];
function blank():BusinessProject{return{id:`business-${Date.now()}`,name:"Untitled Business",sourceId:"",customer:"",offer:"",delivery:"Digital / Remote",pricePosition:"Core",salesMessage:"",operations:["Inquiry","Confirm fit","Collect payment / approval","Deliver","Follow up","Ask for feedback / referral"],growth:"More customers",step:0,progress:5,status:"BUILDING",updatedAt:new Date().toISOString()}}
export default function BusinessBuilderPage(){
 const[project,setProject]=useState<BusinessProject|null>(null);const[creations,setCreations]=useState<UnifiedCreation[]>([]);const[saved,setSaved]=useState(true);
 useEffect(()=>{const list=JSON.parse(localStorage.getItem(KEY)||"[]") as BusinessProject[];const id=localStorage.getItem(ACTIVE);setProject(list.find(x=>x.id===id&&x.status==="BUILDING")||blank());setCreations(readUnifiedCreations())},[]);
 useEffect(()=>{if(!project)return;setSaved(false);const t=setTimeout(()=>{const list=JSON.parse(localStorage.getItem(KEY)||"[]") as BusinessProject[];const next=[project,...list.filter(x=>x.id!==project.id)];localStorage.setItem(KEY,JSON.stringify(next));localStorage.setItem(ACTIVE,project.status==="BUILDING"?project.id:"");setSaved(true)},350);return()=>clearTimeout(t)},[project]);
 const current=project?.step??0;const sources=useMemo(()=>creations.filter(c=>c.status==="COMPLETE"&&["brand","service_offer","digital_product","event_kit"].includes(c.kind)),[creations]);
 function patch(v:Partial<BusinessProject>){setProject(p=>p?{...p,...v,updatedAt:new Date().toISOString()}:p)}
 function next(){if(!project)return;const n=Math.min(project.step+1,steps.length-1);patch({step:n,progress:Math.round(((n+1)/steps.length)*100)})}
 function complete(){if(!project)return;patch({status:"COMPLETE",progress:100});setTimeout(()=>localStorage.setItem(ACTIVE,""),0)}
 if(!project)return null;
 return <main className="cc4-shell"><section className="cc4-hero"><span className="cc4-eyebrow">BUSINESS CENTER · BUSINESS BUILDER</span><h1>TURN PROVEN CREATIONS INTO A SIMPLE BUSINESS SYSTEM.</h1><p>{saved?"Saved ✓":"Saving…"}</p></section>
 <section className="cc5-smart-panel"><div><span className="cc4-eyebrow">CREATOR COACH</span><h2>A BUSINESS IS NOT WHERE YOU START.</h2><p>It is what you can build from something useful that already works. Pick a creation, brand, service, or event system as your starting proof.</p></div></section>
 <section className="cc5-smart-panel"><div><span className="cc4-eyebrow">{steps[current]} · STEP {current+1} OF {steps.length}</span><h2>{steps[current]}</h2><div className="cc4-meter"><span style={{width:`${project.progress}%`}}/></div></div></section><section className="cc4-section">
 {current===0&&<article className="cc5-profile-card"><h2>What are you building from?</h2><div className="cc4-card-grid cc4-grid">{sources.map(s=><button key={`${s.kind}-${s.id}`} className={`cc5-brand-connect ${project.sourceId===s.id?"selected":""}`} onClick={()=>patch({sourceId:s.id,name:s.kind==="brand"?s.title:`${s.title} Business`})}><small>{s.kind.replaceAll("_"," ")}</small><b>{s.title}</b><span>{project.sourceId===s.id?"SELECTED":"USE THIS"}</span></button>)}</div>{!sources.length&&<div className="cc4-empty">You can still build a business, but Creator College works best when you start from something already created.</div>}<input value={project.name==="Untitled Business"?"":project.name} onChange={e=>patch({name:e.target.value||"Untitled Business"})} placeholder="Business name or working name"/><button className="cc4-primary" disabled={project.name==="Untitled Business"} onClick={next}>USE THIS BUSINESS IDEA</button></article>}
 {current===1&&<article className="cc5-profile-card"><h2>Who is the customer?</h2><input value={project.customer} onChange={e=>patch({customer:e.target.value})} placeholder="Who has the problem, need, desire, or opportunity?"/><button className="cc4-primary" disabled={!project.customer.trim()} onClick={next}>NEXT</button></article>}
 {current===2&&<article className="cc5-profile-card"><h2>What is the core offer?</h2><textarea value={project.offer} onChange={e=>patch({offer:e.target.value})} placeholder="I help ___ get ___ through ___"/><button className="cc4-primary" disabled={!project.offer.trim()} onClick={next}>KEEP THIS OFFER</button></article>}
 {current===3&&<article className="cc5-profile-card"><h2>How will you deliver it?</h2><div className="cc5-chips">{["Digital / Remote","Live Call","In Person","Done For You","Recurring Service","Group / Workshop","Hybrid"].map(x=><button key={x} className={project.delivery===x?"selected":""} onClick={()=>patch({delivery:x})}>{x}</button>)}</div><button className="cc4-primary" onClick={next}>USE THIS DELIVERY</button></article>}
 {current===4&&<article className="cc5-profile-card"><h2>Set the pricing position</h2><p>Creator College gives positioning guidance, not earnings promises. Your actual price should reflect time, complexity, customer value, delivery cost, and market reality.</p><div className="cc5-chips">{["Entry","Core","Premium"].map(x=><button key={x} className={project.pricePosition===x?"selected":""} onClick={()=>patch({pricePosition:x})}>{x}</button>)}</div><div className="cc4-card-grid cc4-grid"><div className="cc4-card"><small>ENTRY</small><h3>Easy first yes</h3><p>Small scope, clear result, lower commitment.</p></div><div className="cc4-card"><small>CORE</small><h3>Main offer</h3><p>Your standard useful service or package.</p></div><div className="cc4-card"><small>PREMIUM</small><h3>More support</h3><p>Higher-touch delivery, customization, or larger scope.</p></div></div><button className="cc4-primary" onClick={next}>KEEP THIS POSITION</button></article>}
 {current===5&&<article className="cc5-profile-card"><h2>Build the sales message</h2><textarea value={project.salesMessage} onChange={e=>patch({salesMessage:e.target.value})} placeholder="For [customer], we provide [offer] so they can [result]. Here’s how it works..."/><div className="cc4-mini-actions"><button onClick={()=>patch({salesMessage:`For ${project.customer}, ${project.name} provides ${project.offer}. Delivery is ${project.delivery.toLowerCase()}. The goal is a clear, useful result without unnecessary complexity.`})}>COACH DRAFT</button></div><button className="cc4-primary" disabled={!project.salesMessage.trim()} onClick={next}>USE THIS SALES MESSAGE</button></article>}
 {current===6&&<article className="cc5-profile-card"><h2>Build the operating flow</h2><div className="cc4-family-items">{project.operations.map((x,i)=><div key={i}><span>{i+1}</span><div><input value={x} onChange={e=>patch({operations:project.operations.map((op,idx)=>idx===i?e.target.value:op)})}/></div></div>)}</div><p>Keep the first system boring and reliable: inquiry → agreement → delivery → communication → feedback → repeat.</p><button className="cc4-primary" onClick={next}>KEEP THIS OPERATING FLOW</button></article>}
 {current===7&&<article className="cc5-profile-card"><h2>What should grow next?</h2><div className="cc5-chips">{["More customers","More products","More locations","Partners","Automation","Team","Recurring revenue"].map(x=><button key={x} className={project.growth===x?"selected":""} onClick={()=>patch({growth:x})}>{x}</button>)}</div><button className="cc4-primary" onClick={next}>REVIEW MY BUSINESS</button></article>}
 {current===8&&project.status!=="COMPLETE"&&<article className="cc5-profile-card"><h2>Your business starter system is ready</h2><div className="cc4-review-list"><div><span>✓</span><b>Customer</b><small>{project.customer}</small></div><div><span>✓</span><b>Core offer</b><small>{project.offer}</small></div><div><span>✓</span><b>Delivery</b><small>{project.delivery}</small></div><div><span>✓</span><b>Pricing position</b><small>{project.pricePosition}</small></div><div><span>✓</span><b>Operating flow</b><small>{project.operations.length} steps</small></div><div><span>✓</span><b>Growth focus</b><small>{project.growth}</small></div></div><button className="cc4-primary" onClick={complete}>COMPLETE MY BUSINESS STARTER SYSTEM</button></article>}
 {project.status==="COMPLETE"&&<article className="cc5-smart-panel"><div><span className="cc4-eyebrow">BUSINESS STARTER SYSTEM COMPLETE</span><h2>{project.name} IS READY TO OPERATE.</h2><p>{project.offer} · {project.delivery} · {project.pricePosition} positioning</p><div className="cc4-grid cc4-actions-grid"><a href="/creator-college/desk">✦<b>RETURN TO MY DESK</b><small>Your business is now part of Creator College</small></a><a href="/creator-college/service">💼<b>REFINE AN OFFER</b><small>Build or improve the customer-facing offer</small></a></div></div></article>}
 </section></main>
}
