'use client';

import { useEffect, useMemo, useState } from 'react';

const KEY = 'ccj-open-house-v3';
const schools={video:'Video & TV',voice:'Voice & Podcasting',design:'Design',stories:'Stories',ai:'AI & Digital Creation',business:'Creator Business',ideas:'Big Ideas'};
const picks=[['videos',{video:3,voice:1,stories:1}],['design',{design:3,stories:1,business:1}],['invent',{ideas:3,ai:1,business:1}],['stories',{stories:3,voice:1,video:1}],['tech',{ai:3,ideas:2}],['products',{business:3,design:1,ideas:1}],['perform',{voice:3,video:2}],['worlds',{stories:2,design:1,ideas:2}]];
function score(selected=[]){const r={video:0,voice:0,design:0,stories:0,ai:0,business:0,ideas:0};selected.forEach(id=>{const p=picks.find(x=>x[0]===id);if(p)Object.entries(p[1]).forEach(([k,v])=>r[k]+=v)});return Object.entries(r).sort((a,b)=>b[1]-a[1]).slice(0,3)}
export default function Locker(){const[s,setS]=useState(null);useEffect(()=>{try{const raw=localStorage.getItem(KEY);setS(raw?JSON.parse(raw):null)}catch{setS(null)}},[]);const mix=useMemo(()=>score(s?.picks),[s]);if(!s)return <main className="app"><div className="shell"><section className="card"><div className="eye">CREATOR LOCKER</div><h1 className="title">Nothing saved here yet.</h1><p className="lead">Complete the free Open House first and your Creator ID + first idea will appear here.</p><a className="btn primary" href="/">Start Open House</a></section></div></main>;
return <main className="app"><div className="shell"><div className="topbar"><a className="back" href="/">← Back to Campus</a><div className="brand">CREATOR COLLEGE<b>MY CREATOR LOCKER</b></div></div><section className="card"><div className="eye">PRIVATE STAGING LOCKER</div><h1 className="title">{s.creator || 'Creator'}’s creations.</h1><p className="lead">Saved only on this device until parent authentication and Supabase are connected.</p><div className="reward"><b>{s.avatar || '🎥'} {s.creator || 'Visiting Creator'}</b><span>{s.credits || 0} Creator Credits</span></div><div className="lockerCard"><small>CREATOR ID</small><div className="avatar">{s.avatar || '🎥'}</div><h2>{s.creator || 'Visiting Creator'}</h2><div className="schools">{mix.map(([k])=><span key={k}>{schools[k]}</span>)}</div></div>{s.name&&<div className="lockerCard"><small>MY FIRST CREATOR IDEA</small><div className="avatar">💡</div><h2>{s.name}</h2><p>{s.idea}</p><p className="muted">Made for: {s.audience}</p></div>}<div className="actions"><a className="btn secondary" href="/">Return to Campus</a></div></section></div></main>}
