"use client";

import { useEffect, useMemo, useState } from "react";

type Episode={title:string;hook:string;script:string;visual:string};
type VideoProject={id:string;title:string;audience:string;goal:string;format:string;episodes:Episode[];style:string;posting:string;useMode:string;step:number;progress:number;status:"BUILDING"|"COMPLETE";updatedAt:string;familyId?:string;parentId?:string};
const KEY="creator-college-v1-video-projects";
const ACTIVE="creator-college-v1-video-active";
const steps=["Idea","Audience","Goal","Format","Name","Episodes","Scripts","Visuals","Posting Plan","Review","Use Mode"];
function blank():VideoProject{return{id:`video-${Date.now()}`,title:"Untitled Series",audience:"",goal:"Teach",format:"5 Short Videos",episodes:[],style:"Clean",posting:"3x a week",useMode:"Build my audience",step:0,progress:5,status:"BUILDING",updatedAt:new Date().toISOString()}}
function episodeDraft(title:string,project:VideoProject,index:number){return{title,hook:`Here’s the one thing most people miss about ${title.toLowerCase()}.`,script:`Open with the problem. Explain one clear idea in plain language for ${project.audience||"your audience"}. Give one practical example. End with a simple next step.`,visual:index%2===0?"Talking head + on-screen text":"Voice-over + simple B-roll"}}
export default function VideoBuilderPage(){
 const[project,setProject]=useState<VideoProject|null>(null);const[saved,setSaved]=useState(true);const[activeEpisode,setActiveEpisode]=useState(0);
 useEffect(()=>{const list=JSON.parse(localStorage.getItem(KEY)||"[]") as VideoProject[];const id=localStorage.getItem(ACTIVE);const active=list.find(x=>x.id===id&&x.status==="BUILDING");setProject(active||blank())},[]);
 useEffect(()=>{if(!project)return;setSaved(false);const t=setTimeout(()=>{const list=JSON.parse(localStorage.getItem(KEY)||"[]") as VideoProject[];const next=[project,...list.filter(x=>x.id!==project.id)];localStorage.setItem(KEY,JSON.stringify(next));localStorage.setItem(ACTIVE,project.status==="BUILDING"?project.id:"");setSaved(true)},350);return()=>clearTimeout(t)},[project]);
 const current=project?.step??0;const pct=useMemo(()=>Math.round(((current+1)/steps.length)*100),[current]);
 function patch(v:Partial<VideoProject>){setProject(p=>p?{...p,...v,updatedAt:new Date().toISOString()}:p)}
 function next(){if(!project)return;patch({step:Math.min(project.step+1,steps.length-1),progress:pct})}
 function createEpisodes(){if(!project)return;const names=["The Big Idea","What Most People Get Wrong","The First Step","A Better Way","What To Do Next"];patch({episodes:names.map((n,i)=>episodeDraft(n,project,i))});next()}
 function updateEpisode(i:number,v:Partial<Episode>){if(!project)return;patch({episodes:project.episodes.map((e,idx)=>idx===i?{...e,...v}:e)})}
 function complete(){if(!project)return;patch({status:"COMPLETE",progress:100});setTimeout(()=>{localStorage.setItem(ACTIVE,"")},0)}
 if(!project)return null;
 return <main className="cc4-shell"><section className="cc4-hero"><span className="cc4-eyebrow">CREATOR LAB · VIDEO SERIES</span><h1>TURN ONE IDEA INTO A SERIES PEOPLE CAN WATCH.</h1><p>{saved?"Saved ✓":"Saving…"}</p></section><section className="cc5-smart-panel"><div><span className="cc4-eyebrow">{steps[current]} · STEP {current+1} OF {steps.length}</span><h2>{steps[current]}</h2><div className="cc4-meter"><span style={{width:`${pct}%`}}/></div></div></section>
 <section className="cc4-section">
 {current===0&&<article className="cc5-profile-card"><h2>What is the series about?</h2><textarea value={project.title==="Untitled Series"?"":project.title} onChange={e=>patch({title:e.target.value||"Untitled Series"})} placeholder="Example: Walking Again After 50"/><button className="cc4-primary" disabled={project.title==="Untitled Series"} onClick={next}>USE THIS IDEA</button></article>}
 {current===1&&<article className="cc5-profile-card"><h2>Who is this for?</h2><input value={project.audience} onChange={e=>patch({audience:e.target.value})} placeholder="Example: women 50+ restarting a walking routine"/><button className="cc4-primary" disabled={!project.audience.trim()} onClick={next}>NEXT</button></article>}
 {current===2&&<article className="cc5-profile-card"><h2>What should the series do?</h2><div className="cc5-chips">{["Teach","Entertain","Inspire","Promote","Build audience","Sell","Document","Group use"].map(x=><button key={x} className={project.goal===x?"selected":""} onClick={()=>patch({goal:x})}>{x}</button>)}</div><button className="cc4-primary" onClick={next}>KEEP THIS GOAL</button></article>}
 {current===3&&<article className="cc5-profile-card"><h2>Choose the format</h2><div className="cc5-chips">{["5 Short Videos","3 Deeper Videos","7-Day Series","How-To Series","FAQ Series","Story Series"].map(x=><button key={x} className={project.format===x?"selected":""} onClick={()=>patch({format:x})}>{x}</button>)}</div><button className="cc4-primary" onClick={next}>USE THIS FORMAT</button></article>}
 {current===4&&<article className="cc5-profile-card"><h2>Name the series</h2><input value={project.title} onChange={e=>patch({title:e.target.value})}/><p>Creator Coach tip: clear beats clever for the first version.</p><button className="cc4-primary" onClick={createEpisodes}>BUILD MY EPISODES</button></article>}
 {current===5&&<article className="cc5-profile-card"><h2>Your 5-episode map</h2><div className="cc4-family-items">{project.episodes.map((e,i)=><div key={i}><span>{i+1}</span><div><input value={e.title} onChange={ev=>updateEpisode(i,{title:ev.target.value})}/></div></div>)}</div><button className="cc4-primary" onClick={next}>WRITE THE SCRIPTS</button></article>}
 {current===6&&<article className="cc5-profile-card"><h2>Write each episode</h2><div className="cc5-chips">{project.episodes.map((e,i)=><button key={i} className={activeEpisode===i?"selected":""} onClick={()=>setActiveEpisode(i)}>{i+1}. {e.title}</button>)}</div>{project.episodes[activeEpisode]&&<><input value={project.episodes[activeEpisode].hook} onChange={e=>updateEpisode(activeEpisode,{hook:e.target.value})}/><textarea value={project.episodes[activeEpisode].script} onChange={e=>updateEpisode(activeEpisode,{script:e.target.value})}/><div className="cc4-mini-actions"><button onClick={()=>updateEpisode(activeEpisode,episodeDraft(project.episodes[activeEpisode].title,project,activeEpisode))}>COACH DRAFT</button></div></>}<button className="cc4-primary" onClick={next}>SCRIPTS READY</button></article>}
 {current===7&&<article className="cc5-profile-card"><h2>Choose the visual approach</h2><div className="cc5-chips">{["Clean","Bold","Warm","Modern","Faith","Business"].map(x=><button key={x} className={project.style===x?"selected":""} onClick={()=>patch({style:x})}>{x}</button>)}</div><div className="cc4-family-items">{project.episodes.map((e,i)=><div key={i}><span>{i+1}</span><div><b>{e.title}</b><small>{e.visual}</small></div></div>)}</div><button className="cc4-primary" onClick={next}>USE THIS LOOK</button></article>}
 {current===8&&<article className="cc5-profile-card"><h2>How often will you post?</h2><div className="cc5-chips">{["Daily","3x a week","Weekly","One-time drop"].map(x=><button key={x} className={project.posting===x?"selected":""} onClick={()=>patch({posting:x})}>{x}</button>)}</div><p>Creator Coach will keep the plan realistic and focused on consistency.</p><button className="cc4-primary" onClick={next}>BUILD MY POSTING PLAN</button></article>}
 {current===9&&<article className="cc5-profile-card"><h2>Review the series</h2><div className="cc4-review-list"><div><span>✓</span><b>Clear audience</b><small>{project.audience}</small></div><div><span>✓</span><b>Distinct episodes</b><small>{project.episodes.length} planned</small></div><div><span>✓</span><b>Hooks ready</b><small>{project.episodes.filter(e=>e.hook.trim()).length} of {project.episodes.length}</small></div><div><span>✓</span><b>Posting rhythm</b><small>{project.posting}</small></div></div><button className="cc4-primary" onClick={next}>READY TO FINISH</button></article>}
 {current===10&&project.status!=="COMPLETE"&&<article className="cc5-profile-card"><h2>What do you want this series to do?</h2><div className="cc5-chips">{["Personal","Audience Growth","Promote","Sell","Church / Group","Client","Fun"].map(x=><button key={x} className={project.useMode===x?"selected":""} onClick={()=>patch({useMode:x})}>{x}</button>)}</div><button className="cc4-primary" onClick={complete}>COMPLETE MY SERIES</button></article>}
 {project.status==="COMPLETE"&&<article className="cc5-smart-panel"><div><span className="cc4-eyebrow">CREATION COMPLETE</span><h2>YOUR SERIES IS READY TO SHOOT.</h2><p><b>{project.title}</b> · {project.episodes.length} episodes · {project.style} · {project.posting}</p><div className="cc4-grid cc4-actions-grid"><a href="/creator-college/locker">▦<b>SAVE TO LOCKER</b><small>Keep the series with your other creations</small></a><a href="/creator-college">✹<b>EXPLODE THIS</b><small>Turn it into a guide, email or audio series</small></a></div></div></article>}
 </section></main>
}
