"use client";

import { useEffect, useState } from "react";

type ServiceProject={id:string;skill:string;problem:string;customer:string;offer:string;delivery:string;scope:string[];priceTier:string;priceNote:string;promo:string;salesMessage:string;followup:string;step:number;progress:number;status:"BUILDING"|"COMPLETE";updatedAt:string;familyId?:string;parentId?:string};
const KEY="creator-college-v1-service-projects";const ACTIVE="creator-college-v1-service-active";
const steps=["Skill","Problem","Customer","Offer","Delivery","Price","Promotion","Sales Message","Review"];
function blank():ServiceProject{return{id:`service-${Date.now()}`,skill:"",problem:"",customer:"",offer:"",delivery:"Done-for-you",scope:[],priceTier:"Starter",priceNote:"",promo:"",salesMessage:"",followup:"",step:0,progress:5,status:"BUILDING",updatedAt:new Date().toISOString()}}
function coachOffer(p:ServiceProject){return `I help ${p.customer||"a specific customer"} ${p.problem?`solve ${p.problem.toLowerCase()}`:"get a clear result"} by providing ${p.skill||"a focused service"}.`}
function promoDraft(p:ServiceProject){return `${p.offer}\n\nA simple service for ${p.customer}. Clear scope, clear next step, no unnecessary complexity.`}
export default function ServiceOfferPage(){
 const[project,setProject]=useState<ServiceProject|null>(null);const[saved,setSaved]=useState(true);
 useEffect(()=>{const list=JSON.parse(localStorage.getItem(KEY)||"[]") as ServiceProject[];const id=localStorage.getItem(ACTIVE);setProject(list.find(x=>x.id===id&&x.status==="BUILDING")||blank())},[]);
 useEffect(()=>{if(!project)return;setSaved(false);const t=setTimeout(()=>{const list=JSON.parse(localStorage.getItem(KEY)||"[]") as ServiceProject[];const next=[project,...list.filter(x=>x.id!==project.id)];localStorage.setItem(KEY,JSON.stringify(next));localStorage.setItem(ACTIVE,project.status==="BUILDING"?project.id:"");setSaved(true)},350);return()=>clearTimeout(t)},[project]);
 function patch(v:Partial<ServiceProject>){setProject(p=>p?{...p,...v,updatedAt:new Date().toISOString()}:p)}
 function next(){if(!project)return;const n=Math.min(project.step+1,steps.length-1);patch({step:n,progress:Math.round(((n+1)/steps.length)*100)})}
 function complete(){if(!project)return;patch({status:"COMPLETE",progress:100,familyId:project.familyId||`family-${project.id}`});setTimeout(()=>localStorage.setItem(ACTIVE,""),0)}
 if(!project)return null;const s=project.step;
 return <main className="cc4-shell"><section className="cc4-hero"><span className="cc4-eyebrow">CREATE TO EARN · SIMPLE SERVICE OFFER</span><h1>TURN WHAT YOU KNOW INTO SOMETHING PEOPLE CAN USE.</h1><p>{saved?"Saved ✓":"Saving…"}</p></section><section className="cc5-smart-panel"><div><span className="cc4-eyebrow">{steps[s]} · STEP {s+1} OF {steps.length}</span><h2>{steps[s]}</h2><div className="cc4-meter"><span style={{width:`${project.progress}%`}}/></div></div></section><section className="cc4-section">
 {s===0&&<article className="cc5-profile-card"><h2>What can you do well enough to help someone?</h2><div className="cc5-chips">{["Design","Social Media","Teaching","Writing","Organization","Photography","Video","Beauty","Cooking","Home Help","Business Help","Ministry Support"].map(x=><button key={x} className={project.skill===x?"selected":""} onClick={()=>patch({skill:x})}>{x}</button>)}</div><input value={project.skill} onChange={e=>patch({skill:e.target.value})} placeholder="Or describe your skill"/><button className="cc4-primary" disabled={!project.skill.trim()} onClick={next}>USE THIS SKILL</button></article>}
 {s===1&&<article className="cc5-profile-card"><h2>What problem can you help solve?</h2><textarea value={project.problem} onChange={e=>patch({problem:e.target.value})} placeholder="Example: small businesses struggle to keep up with weekly social posts"/><button className="cc4-primary" disabled={!project.problem.trim()} onClick={next}>KEEP THIS PROBLEM</button></article>}
 {s===2&&<article className="cc5-profile-card"><h2>Who needs this most?</h2><input value={project.customer} onChange={e=>patch({customer:e.target.value})} placeholder="Example: local salons and barbershops"/><button className="cc4-primary" disabled={!project.customer.trim()} onClick={()=>{patch({offer:coachOffer(project)});next()}}>BUILD MY OFFER</button></article>}
 {s===3&&<article className="cc5-profile-card"><h2>Make the offer clear</h2><textarea value={project.offer} onChange={e=>patch({offer:e.target.value})}/><p>Creator Coach pattern: I help ___ get ___ by providing ___.</p><button className="cc4-primary" disabled={!project.offer.trim()} onClick={next}>KEEP THIS OFFER</button></article>}
 {s===4&&<article className="cc5-profile-card"><h2>How will you deliver it?</h2><div className="cc5-chips">{["Done-for-you","1:1 Call","In person","Digital delivery","Recurring monthly","Workshop","At their location"].map(x=><button key={x} className={project.delivery===x?"selected":""} onClick={()=>patch({delivery:x})}>{x}</button>)}</div><h3>What is included?</h3><div className="cc5-chips">{["Planning","1 revision","Finished file","30-minute call","Setup","Follow-up","Simple report","Custom branding"].map(x=><button key={x} className={project.scope.includes(x)?"selected":""} onClick={()=>patch({scope:project.scope.includes(x)?project.scope.filter(v=>v!==x):[...project.scope,x]})}>{x}</button>)}</div><button className="cc4-primary" onClick={next}>LOCK THE SCOPE</button></article>}
 {s===5&&<article className="cc5-profile-card"><h2>Choose a starting price position</h2><p>This is guidance, not an earnings promise. The right price depends on time, complexity, customer, materials, local market and experience.</p><div className="cc5-chips">{["Starter","Standard","Premium"].map(x=><button key={x} className={project.priceTier===x?"selected":""} onClick={()=>patch({priceTier:x,priceNote:x==="Starter"?"Keep the first offer easy to say yes to and tightly scoped.":x==="Standard"?"Price for a complete useful result, not just your time.":"Use only when the service includes higher-touch work, complexity, access, or customization."})}>{x}</button>)}</div><div className="cc4-empty">{project.priceNote||"Choose a position to see guidance."}</div><button className="cc4-primary" onClick={()=>{patch({promo:promoDraft(project)});next()}}>CREATE MY PROMOTION</button></article>}
 {s===6&&<article className="cc5-profile-card"><h2>Promotion copy</h2><textarea value={project.promo} onChange={e=>patch({promo:e.target.value})}/><div className="cc4-grid cc4-card-grid"><div className="cc4-card"><small>SOCIAL</small><h3>Short post</h3><p>{project.offer}</p></div><div className="cc4-card"><small>TEXT / DM</small><h3>Conversation starter</h3><p>I’m offering a simple new service for {project.customer}. Want me to send the details?</p></div><div className="cc4-card"><small>EMAIL</small><h3>Short outreach</h3><p>I created a focused service to help with {project.problem.toLowerCase()}. Happy to send the simple scope.</p></div></div><button className="cc4-primary" onClick={()=>{patch({salesMessage:`${project.offer}\n\nWhat’s included: ${project.scope.join(", ")||"a clearly defined result"}.\nDelivery: ${project.delivery}.\nStarting position: ${project.priceTier}.`});next()}}>BUILD SALES MESSAGE</button></article>}
 {s===7&&<article className="cc5-profile-card"><h2>Your simple sales message</h2><textarea value={project.salesMessage} onChange={e=>patch({salesMessage:e.target.value})}/><h3>After delivery</h3><textarea value={project.followup} onChange={e=>patch({followup:e.target.value})} placeholder="Thank them, ask for feedback, request a referral, or offer the next useful step."/><button className="cc4-primary" onClick={next}>REVIEW MY OFFER</button></article>}
 {s===8&&project.status!=="COMPLETE"&&<article className="cc5-profile-card"><h2>Your service offer is ready</h2><div className="cc4-review-list"><div><span>✓</span><b>Specific customer</b><small>{project.customer}</small></div><div><span>✓</span><b>Clear result</b><small>{project.problem}</small></div><div><span>✓</span><b>Defined delivery</b><small>{project.delivery} · {project.scope.length} included items</small></div><div><span>✓</span><b>Commercial package</b><small>{project.priceTier} position · promotion + sales message ready</small></div></div><button className="cc4-primary" onClick={complete}>COMPLETE MY SERVICE OFFER</button></article>}
 {project.status==="COMPLETE"&&<article className="cc5-smart-panel"><div><span className="cc4-eyebrow">CREATE TO EARN · COMPLETE</span><h2>YOUR SIMPLE SERVICE OFFER IS READY.</h2><p>{project.offer}</p><div className="cc4-grid cc4-actions-grid"><a href="/creator-college/locker">▦<b>SAVE TO LOCKER</b><small>Keep the offer with your other creations</small></a><a href="/creator-college">✹<b>EXPLODE THIS</b><small>Turn it into a guide, workshop or business</small></a></div></div></article>}
 </section></main>
}
