import test from 'node:test';
import assert from 'node:assert/strict';
import { GET, POST } from '../app/api/internal/hotel-audio/route.ts';
const token='test-operator-token-which-is-long-enough';
const original=global.fetch;
function setup(){process.env.HOTEL_AUDIO_OPERATOR_TOKEN=token;process.env.HOTEL_AUDIO_OPERATOR_EXPIRES_AT=new Date(Date.now()+60000).toISOString();process.env.ELEVENLABS_API_KEY='test-provider-key';process.env.HOTEL_AUDIO_GENERATION_ENABLED='false';delete process.env.HOTEL_AUDIO_APPROVED_VOICE_IDS;}
function request(action,body){return new Request('https://studio.example/api/internal/hotel-audio?action='+action,{headers:{authorization:'Bearer '+token,'content-type':'application/json'},...(body?{method:'POST',body:JSON.stringify(body)}:{})});}
test('unauthorized and expired requests cannot call the provider',async()=>{setup();let calls=0;global.fetch=async()=>{calls++;throw Error('must not call');};assert.equal((await GET(new Request('https://studio.example'))).status,401);process.env.HOTEL_AUDIO_OPERATOR_EXPIRES_AT='2000-01-01';assert.equal((await GET(request('voices'))).status,503);assert.equal(calls,0);});
test('voice discovery uses server key and excludes account/private verification fields',async()=>{setup();global.fetch=async(url,options)=>{assert.match(url,/^https:\/\/api\.elevenlabs\.io\/v2\/voices\?/);assert.equal(options.headers['xi-api-key'],'test-provider-key');return Response.json({voices:[{voice_id:'abc',name:'Example',preview_url:'https://example.com/voice.mp3',voice_verification:{private:'private'},sharing:{whitelisted_emails:['private@example.com']}}],has_more:false});};const response=await GET(request('voices'));const data=await response.json();assert.equal(data.voices[0].name,'Example');assert.equal(data.voices[0].sharing,undefined);assert.equal(data.voices[0].voice_verification,undefined);assert.equal(response.headers.get('cache-control'),'private, no-store');});
test('disabled generation and unapproved voices never spend credits',async()=>{setup();let calls=0;global.fetch=async()=>{calls++;throw Error('must not call');};assert.equal((await POST(request('',{action:'sound-effect',cue_id:'reception-bell'}))).status,403);process.env.HOTEL_AUDIO_GENERATION_ENABLED='true';assert.equal((await POST(request('',{action:'speech',voice_id:'unknownvoice123',text:'hello'}))).status,403);assert.equal((await POST(request('',{action:'sound-effect',cue_id:'toString'}))).status,400);assert.equal(calls,0);});
test('sound cues are bounded, return audio and never echo sensitive provider errors',async()=>{setup();process.env.HOTEL_AUDIO_GENERATION_ENABLED='true';global.fetch=async(url,options)=>{assert.match(url,/\/v1\/sound-generation\?/);assert.equal(JSON.parse(options.body).duration_seconds,2);return new Response(new Uint8Array(256),{headers:{'Content-Type':'audio/mpeg','character-cost':'40'}});};const result=await POST(request('',{action:'sound-effect',cue_id:'reception-bell'}));assert.equal(result.status,200);assert.equal(result.headers.get('x-elevenlabs-character-cost'),'40');global.fetch=async()=>Response.json({detail:{status:'missing_permissions',message:'secret-key-value'}},{status:401});const failed=await GET(request('voices'));assert.deepEqual(await failed.json(),{error:'missing_permissions',provider:'elevenlabs',provider_status:401});global.fetch=original;});
test('voice design rejects oversized inputs and returns previews without saving voices',async()=>{setup();process.env.HOTEL_AUDIO_GENERATION_ENABLED='true';let calls=0;const description='A warm clear conversational narrator voice for a fictional character.';const text='Welcome to this short voice audition. Please speak clearly and naturally, with a warm conversational tone and comfortable pauses.';global.fetch=async(url,options)=>{calls++;assert.match(url,/\/v1\/text-to-voice\/design\?/);const body=JSON.parse(options.body);assert.equal(body.text,text);assert.equal(body.voice_description,description);assert.equal(body.reference_audio_base64,undefined);return Response.json({previews:[{audio_base_64:Buffer.alloc(256).toString('base64'),generated_voice_id:'audition1234567890',media_type:'audio/mpeg',duration_secs:12}],text:body.text});};assert.equal((await POST(request('',{action:'voice-design',text:'x'.repeat(301),voice_description:description}))).status,400);const response=await POST(request('',{action:'voice-design',text,voice_description:description,reference_audio_base64:'ignored'}));assert.equal(response.status,200);const result=await response.json();assert.equal(result.previews.length,1);assert.equal(result.text,text);assert.equal(calls,1);global.fetch=original;});
