(()=>{const $=s=>document.querySelector(s),status=message=>$('#status').textContent=message;let secret=location.hash.slice(1),party=null;history.replaceState(null,'',location.pathname);async function api(path,method='GET',data){const r=await fetch(path,{method,credentials:'same-origin',headers:method==='GET'?{}:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const result=await r.json();if(!r.ok)throw new Error(result.error||'Please try again.');return result;}
const lists=[['menu','Menu'],['shoppingList','Shopping list'],['contributionSuggestions','What sisters can bring'],['checklist','Host checklist'],['conversationQuestions','Conversation cards']];for(const [key,title] of lists){const label=document.createElement('label');label.textContent=title+' — one item per line';const input=document.createElement('textarea');input.name=key;input.rows=5;input.maxLength=5000;label.append(input);$('#lists').append(label);}
async function load(){try{const host=await api('/api/host');party=await api('/api/parties/'+host.partyId);$('#host').hidden=false;$('#access').hidden=true;$('#recover').hidden=true;for(const name of ['partyTitle','description','preferredDate','preferredTime','timeZone'])$('#edit').elements[name].value=party.plan[name]||'';for(const [key] of lists)$('#edit').elements[key].value=party.plan[key].join('\n');status('Your private party is saved.');}catch(e){status(e.message);$('#recover').hidden=false;}}
if(secret){$('#access').hidden=false;$('#confirm').onclick=async()=>{$('#confirm').disabled=true;try{await api('/api/access/confirm','POST',{token:secret});secret='';history.replaceState(null,'','/garden-party/host');await load();}catch(e){status(e.message);$('#confirm').disabled=false;}};}else load();
$('#recovery').onsubmit=async event=>{event.preventDefault();try{const result=await api('/api/access/request','POST',{email:$('#recovery').elements.email.value,passwordlessPermission:$('#recovery').elements.permission.checked});status(result.message);}catch(e){status(e.message);}};
$('#edit').onsubmit=async event=>{event.preventDefault();const plan={...party.plan};for(const name of ['partyTitle','description','preferredDate','preferredTime','timeZone'])plan[name]=$('#edit').elements[name].value;for(const [key] of lists)plan[key]=$('#edit').elements[key].value.split('\n').map(x=>x.trim()).filter(Boolean);try{const result=await api('/api/parties/'+party.id,'PATCH',{version:party.version,plan});party={...party,plan,version:result.version};status('Your changes are saved.');}catch(e){status(e.message);}};
$('#signout').onclick=async()=>{try{await api('/api/logout','POST',{});$('#host').hidden=true;status('You are signed out.');$('#recover').hidden=false;}catch(e){status(e.message);}};
$('#delete').onclick=async()=>{if(!confirm('Delete this saved party? This cannot be undone.'))return;try{await api('/api/parties/'+party.id,'DELETE',{});$('#host').hidden=true;status('Your party has been deleted.');}catch(e){status(e.message);}};
})();
